### ISSUE TITLE
Gradle Build doesn't work

### ISSUE THREAD

**Issue by YeahOMA** [Crystallinqq2/qqAntiVirus#5]
I have major trust issues as of late, so I went ahead and built the .JAR myself with Gradle.

Yes, I have a JDK and everything set up. The build compiled correctly but when I run it in the command prompt this happens-

```
welcome 2 qqAntiVirus by Crystallinqq :3
checking versions json shit.
backmeme found!!! cleaning.
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONObject
        at com.qqtechnologies.antivirus.Main.clean(Main.java:61)
        at com.qqtechnologies.antivirus.Main.main(Main.java:42)
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

```

**Comment by YeahOMA** [comment]
Oh wait never mind I didn't compile it with json library

**Comment by Crystallinqq2** [comment]
gradlew shadowJar
